#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/beautysalon
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto=: update
    #spring.jpa.properties.hibernate.dialect=org.hibernate.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true